name: build

on:
  workflow_run:
    workflows: [ "sonar-check" ]
    types: [ completed ]
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: run app
        run: |
          sudo docker compose up -d --build
