name: build

on:
  workflow_run:
    workflows: [ "sonar-check", "spotbugs-check" ]
    types: [ completed ]
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: run app
        run: |
          sudo docker compose up -d --build
