name: secrets-check

on:
  push:
  pull_request:

env:
  DEFECTDOJO_SCAN_TYPE: "Gitleaks Scan"
  DEFECTDOJO_SCAN_TEST_TYPE: "Gitleaks Scan"
  DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
  DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
  DEFECTDOJO_ENGAGEMENT_PERIOD: 7

jobs:
  secret_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.26.0/gitleaks_8.26.0_linux_x64.tar.gz | tar xz -C /usr/local/bin
          chmod +x /usr/local/bin/gitleaks
          gitleaks version
          
      - name: Run Gitleaks scan
        continue-on-error: true
        run: |
          gitleaks detect \
            --source=. \
            --verbose \
            --report-format=json \
            --report-path=gitleaks-report.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
          retention-days: 7

      - name: Create an engagement
        run: |
          TODAY=$(date +%Y-%m-%d)
          ENDDAY=$(date -d "+${DEFECTDOJO_ENGAGEMENT_PERIOD} days" +%Y-%m-%d)

          RESPONSE=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
            -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "CI/CD engagement Gitleaks",
              "target_start": "'"$TODAY"'",
              "target_end": "'"$ENDDAY"'",
              "status": "In Progress",
              "engagement_type": "CI/CD",
              "product": '"${DEFECTDOJO_PRODUCT_ID}"'
              }')
          ENGAGEMENT_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
          echo "ENGAGEMENT_ID=$ENGAGEMENT_ID" >> $GITHUB_ENV
          echo "id=$ENGAGEMENT_ID" >> $GITHUB_OUTPUT

      - name: Upload to DefectDojo
        run: |
          curl -v --fail --location --request POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
          --header "Authorization: Token $DEFECTDOJO_TOKEN" \
          --form "scan_type=$DEFECTDOJO_SCAN_TYPE" \
          --form "engagement=$ENGAGEMENT_ID" \
          --form "file=@gitleaks-report.json;type=application/json" \
          --form "test_type=$DEFECTDOJO_SCAN_TEST_TYPE" \
          --form "verified=true" \
          --form "active=true" \
          --form "minimum_severity=Low" \
          --form "close_old_findings=true" \
          --form "push_to_jira=false"