name: dt-check

on:
  push:
  pull_request:

env:
  DEFECTDOJO_SCAN_TYPE: "Dependency Track Finding Packaging Format (FPF) Export"
  DEFECTDOJO_SCAN_TEST_TYPE: "Dependency Track Scan"
  DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
  DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
  DEFECTDOJO_ENGAGEMENT_PERIOD: 7

jobs:
  dt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run SBOM generator and send report
        run: |
          mvn compile -f pom.xml
          mvn package
          mvn dependency-track:upload-bom -f pom.xml

      - name: Get report
        run: |
          curl -v -L 'http://83.222.27.166:8080/api/v1/finding/project/55eef397-55b2-49a8-a409-a7b92ad1db24/export' -H 'X-Api-Key: odt_zn97YlI0_LKFt7mznDlAtRdD3BsNc6WjOHS1YiPBB' > dt_report.json
      - name: Create an engagement
        run: |
          TODAY=$(date +%Y-%m-%d)
          ENDDAY=$(date -d "+${DEFECTDOJO_ENGAGEMENT_PERIOD} days" +%Y-%m-%d)

          RESPONSE=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
            -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "CI/CD engagement Dependency Track",
              "target_start": "'"$TODAY"'",
              "target_end": "'"$ENDDAY"'",
              "status": "In Progress",
              "engagement_type": "CI/CD",
              "product": 1
              }')
          ENGAGEMENT_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
          echo "ENGAGEMENT_ID=$ENGAGEMENT_ID" >> $GITHUB_ENV
          echo "id=$ENGAGEMENT_ID" >> $GITHUB_OUTPUT

      - name: Upload to DefectDojo
        run: |
          curl --location --request POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            --header "Authorization: Token $DEFECTDOJO_TOKEN" \
            --form "minimum_severity=Info" \
            --form "active=true" \
            --form "verified=true" \
            --form "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            --form "engagement=$ENGAGEMENT_ID" \
            --form "file=@dt_report.json" \
            --form "push_to_jira=false" \
            --form "test_type=$DEFECTDOJO_SCAN_TEST_TYPE"