name: Gitleaks scan
on:
  push:
    branches: [ main ]
  pull_request:
  
jobs:
  secret_scan:
    runs-on: ubuntu-latest
    env:
      # Должны быть определены в Settings → Secrets
      DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
      DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
      DEFECTDOJO_ENGAGEMENT_PERIOD: 7
      DEFECTDOJO_SCAN_TYPE: "Gitleaks Scan"
      DEFECTDOJO_SCAN_TEST_TYPE: "Static Code Analysis"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format json --report-path gitleaks_report.json

      - name: Create an engagement
        run: |
          TODAY=$(date +%Y-%m-%d)
          ENDDAY=$(date -d "+${DEFECTDOJO_ENGAGEMENT_PERIOD} days" +%Y-%m-%d)

          RESPONSE=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
            -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "CI/CD engagement Gitleaks",
              "target_start": "'"$TODAY"'",
              "target_end": "'"$ENDDAY"'",
              "status": "In Progress",
              "engagement_type": "CI/CD",
              "product": '"${DEFECTDOJO_PRODUCT_ID}"'
              }')
          ENGAGEMENT_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
          echo "ENGAGEMENT_ID=$ENGAGEMENT_ID" >> $GITHUB_ENV
          echo "id=$ENGAGEMENT_ID" >> $GITHUB_OUTPUT

      - name: Upload to DefectDojo
        run: |
          curl --fail --location --request POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            --header "Authorization: Token $DEFECTDOJO_TOKEN" \
            --form "minimum_severity=Low" \
            --form "active=true" \
            --form "verified=true" \
            --form "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            --form "engagement=$ENGAGEMENT_ID" \
            --form "file=@gitleaks_report.json" \
            --form "push_to_jira=false" \
            --form "test_type=$DEFECTDOJO_SCAN_TEST_TYPE"
