name: Secrets Scan

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  gitleaks_scan:
    name: Gitleaks → DefectDojo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        run: |
          curl -sSfL https://raw.githubusercontent.com/zricethezav/gitleaks/master/install.sh | bash

      - name: Run Gitleaks
        run: |
          gitleaks detect \
            --source . \
            --config .gitleaks.toml \
            --report-format=json \
            --report-path=report.json
        continue-on-error: true

      - name: Upload Gitleaks report
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: report.json
          retention-days: 7

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install DefectDojo client
        run: pip install defectdojo-api-client

      - name: Convert report → DefectDojo format
        run: python scripts/convert_to_defectdojo.py report.json dd_findings.json

      - name: Send findings to DefectDojo
        env:
          DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
          DEFECTDOJO_API_KEY: ${{ secrets.DEFECTDOJO_TOKEN }}
        run: |
          defectdojo-client \
            --url "$DEFECTDOJO_URL" \
            --api-key "$DEFECTDOJO_TOKEN" \
            import findings --scan dd_findings.json

      - name: Upload DefectDojo findings
        uses: actions/upload-artifact@v3
        with:
          name: defectdojo-findings
          path: dd_findings.json
          retention-days: 7
