name: sonar-check

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  DEFECTDOJO_SCAN_TYPE: "SonarQube Scan"
  DEFECTDOJO_SCAN_TEST_TYPE: "GitHub Actions SonarQube Scan"
  DEFECTDOJO_URL: ${{ secrets.DEFECTDOJO_URL }}
  DEFECTDOJO_TOKEN: ${{ secrets.DEFECTDOJO_TOKEN }}
  DEFECTDOJO_ENGAGEMENT_PERIOD: 7

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Run SonarQube Scan
        run: |
          mvn compile -f pom.xml
          mvn sonar:sonar \
            -Dsonar.host.url=http://176.108.253.3:9000 \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Get report
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }}: "http://176.108.253.3:9000/api/issues/search?componentKeys=com.scalesec:vulnado&ps=500&format=json" > sonarqube_report.json

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-report
          path: sonarqube_report.json
          retention-days: 7

      - name: Create an engagement
        run: |
          TODAY=$(date +%Y-%m-%d)
          ENDDAY=$(date -d "+${DEFECTDOJO_ENGAGEMENT_PERIOD} days" +%Y-%m-%d)

          RESPONSE=$(curl -s -X POST "${DEFECTDOJO_URL}/api/v2/engagements/" \
            -H "Authorization: Token ${DEFECTDOJO_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{
              "name": "CI/CD engagement SonarQube",
              "target_start": "'"$TODAY"'",
              "target_end": "'"$ENDDAY"'",
              "status": "In Progress",
              "engagement_type": "CI/CD",
              "product": 1
              }')
          ENGAGEMENT_ID=$(echo "$RESPONSE" | jq -r '.id // empty')
          echo "ENGAGEMENT_ID=$ENGAGEMENT_ID" >> $GITHUB_ENV
          echo "id=$ENGAGEMENT_ID" >> $GITHUB_OUTPUT

      - name: Upload to DefectDojo
        run: |
          curl --fail --location --request POST "$DEFECTDOJO_URL/api/v2/import-scan/" \
            --header "Authorization: Token $DEFECTDOJO_TOKEN" \
            --form "minimum_severity=Info" \
            --form "active=true" \
            --form "verified=true" \
            --form "scan_type=$DEFECTDOJO_SCAN_TYPE" \
            --form "engagement=$ENGAGEMENT_ID" \
            --form "file=@sonarqube_report.json" \
            --form "push_to_jira=false" \
            --form "test_type=$DEFECTDOJO_SCAN_TEST_TYPE"